openapi: 3.0.1
info:
  title: Oakdoor Enterprise Diode Management Interface API
  description: The Oakdoor Enterprise Diode Management Interface API specification
  version: 0.0.1
servers:
  - url: /api
paths:
  /config/diode:
    get:
      summary: download diode config
      operationId: management_interface.ManagementInterface.do_config_get
      responses:
        200:
          description: diode config available
          content:
            application/json:
              schema:
                type: object
    put:
      summary: Upload diode config
      operationId: management_interface.ManagementInterface.do_config_update
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Diode config successfully uploaded. Power cycle the diode to
            apply.
          content: {}
        500:
          description: Diode config update failed.
          content: {}
  /config/diode/schema:
    get:
      summary: download diode config schema
      operationId: management_interface.ManagementInterface.get_config_schema
      responses:
        200:
          description: diode config schema available
          content:
            application/json:
              schema:
                type: object
  /command/diode/power/on:
    post:
      summary: Turn diode on
      operationId: management_interface.ManagementInterface.do_power_on_procedure
      responses:
        200:
          description: ""
          content: {}
  /command/diode/power/off:
    post:
      summary: Turn diode off
      operationId: management_interface.ManagementInterface.do_power_off_procedure
      responses:
        200:
          description: ""
          content: {}
  /status/version:
    get:
      summary: Platform Status information
      operationId: management_interface.ManagementInterface.do_get_status_version
      responses:
        200:
          description: ""
  /status/latest:
    get:
      summary: Obtain the latest statistics, counters and status information from
        the board
      operationId: management_interface.ManagementInterface.do_get_status_latest
      responses:
        200:
          description: ""
