
ingress:
    useDhcp: False # if true, adapter settings needed?
    ping: True
    mtu: 9000
    adapter1:
        ip: 192.168.1.10
        nm: 255.255.255.0
        gw: 192.168.1.1
        ntp: 192.168.1.3
        log: 192.168.1.4

    adapter2:
        ip: 192.168.1.15
        nm: 255.255.255.0
        gw: 192.168.1.1
        ntp: 192.168.1.3
        log: 192.168.1.4

egress:
    useDhcp: False
    ping: True
    mtu: 9000 # greater than ingress mtu
    adapter1:
        ip: 192.168.1.15
        nm: 255.255.255.0
        gw: 192.168.1.1
        ntp: 192.168.1.3
        log: 192.168.1.4

    adapter2:
        ip: 192.168.1.15
        nm: 255.255.255.0
        gw: 192.168.1.1
        ntp: 192.168.1.3
        log: 192.168.1.4

routingTable: # ingress ports within 1024 block
    - 40001:emulator_tester_1:50001
    - 41024:emulator_tester_1:51024
